<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-6DKMVGB" failures="1" tests="5" name="Default test" time="45.976" errors="0" timestamp="2022-07-09T23:45:30 IST">
  <testcase classname="com.testdemo.unittest.login" name="login_home" time="0.035">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;org.apache.poi.xssf.usermodel.XSSFWorkbook.getSheet(String)&amp;quot; because &amp;quot;com.testdemo.DataProvider.ExcelDataProvider.wb&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.xssf.usermodel.XSSFWorkbook.getSheet(String)" because "com.testdemo.DataProvider.ExcelDataProvider.wb" is null
at com.testdemo.DataProvider.ExcelDataProvider.ExcelDatavalue(ExcelDataProvider.java:40)
at com.testdemo.unittest.login.login_home(login.java:12)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- login_home -->
  <testcase classname="com.testdemo.Testcases.Logintest" name="test" time="10.584"/>
  <testcase classname="com.testdemo.Testcases.LogoutTest" name="test" time="8.108"/>
  <testcase classname="com.testdemo.unittest.extent_reports" name="test" time="0.213"/>
  <testcase classname="com.testdemo.unittest.Configdatareder" name="readconfigfile" time="0.009"/>
  <testcase classname="com.testdemo.pages.BaseClass" name="@BeforeSuite StattusReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite StattusReport -->
  <testcase classname="com.testdemo.pages.BaseClass" name="@BeforeSuite StattusReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite StattusReport -->
</testsuite> <!-- Default test -->
